# Generated by Django 5.2.5 on 2025-08-25 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academia_core', '0003_alter_plan_non_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteprofesorado',
            name='plan',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='inscripciones',
                to='academia_core.planestudios'
            ),
        ),
    ]