# Generated by Django 5.2.5 on 2025-08-30 04:20

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # --- Modelos que probablemente ya existen ---
                migrations.CreateModel(
                    name='Docente',
                    fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('apellido_nombre', models.CharField(max_length=255)), ('dedicacion', models.CharField(blank=True, default='', max_length=32)), ('email', models.EmailField(blank=True, default='', max_length=254))],
                    options={'db_table': 'academia_horarios_docente'},
                ),
                migrations.CreateModel(
                    name='Materia',
                    fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('codigo', models.CharField(blank=True, default='', max_length=32)), ('nombre', models.CharField(max_length=255))],
                    options={'db_table': 'academia_horarios_materia'},
                ),
                migrations.CreateModel(
                    name='Profesorado',
                    fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('nombre', models.CharField(max_length=255, unique=True))],
                    options={'db_table': 'academia_horarios_profesorado'},
                ),
                migrations.CreateModel(
                    name='Plan',
                    fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('nombre', models.CharField(max_length=255)), ('codigo', models.CharField(blank=True, default='', max_length=64)), ('profesorados', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academia_horarios.profesorado'))],
                    options={'db_table': 'academia_horarios_plan', 'unique_together': {('profesorados', 'codigo')}},
                ),
                migrations.CreateModel(
                    name='Periodo',
                    fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('ciclo_lectivo', models.PositiveIntegerField()), ('cuatrimestre', models.PositiveSmallIntegerField(choices=[(1, '1°'), (2, '2°')]))],
                    options={'db_table': 'academia_horarios_periodo', 'unique_together': {('ciclo_lectivo', 'cuatrimestre')}},
                ),
                migrations.CreateModel(
                    name='TimeSlot',
                    fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('dia_semana', models.PositiveSmallIntegerField()), ('inicio', models.TimeField()), ('fin', models.TimeField())],
                    options={'db_table': 'academia_horarios_timeslot'},
                ),
                # --- Modelos que son definitivamente nuevos o modificados ---
                migrations.CreateModel(
                    name='MateriaEnPlan',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('anio', models.PositiveSmallIntegerField()),
                        ('tipo_dictado', models.CharField(choices=[('ANUAL', 'Anual'), ('CUATRIMESTRAL', 'Cuatrimestral')], max_length=16)),
                        ('horas_catedra_semana_1c', models.PositiveSmallIntegerField(default=0)),
                        ('horas_catedra_semana_2c', models.PositiveSmallIntegerField(default=0)),
                        ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academia_horarios.materia')),
                        ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academia_horarios.plan')),
                    ],
                    options={'unique_together': {('plan', 'materia', 'anio')}},
                ),
                migrations.CreateModel(
                    name='Comision',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('turno', models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('vespertino', 'Vespertino'), ('sabado', 'Sábado')], max_length=16)),
                        ('nombre', models.CharField(default='Única', max_length=16)),
                        ('cupo', models.PositiveSmallIntegerField(default=0)),
                        ('materia_en_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academia_horarios.materiaenplan')),
                        ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academia_horarios.periodo')),
                    ],
                    options={'unique_together': {('materia_en_plan', 'periodo', 'nombre')}},
                ),
                migrations.CreateModel(
                    name='HorarioClase',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('aula', models.CharField(blank=True, default='', max_length=64)),
                        ('observaciones', models.TextField(blank=True, default='')),
                        ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academia_horarios.comision')),
                        ('docentes', models.ManyToManyField(blank=True, to='academia_horarios.docente')),
                        ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academia_horarios.timeslot')),
                    ],
                    options={'db_table': 'academia_horarios_horarioclase', 'unique_together': {('comision', 'timeslot')}},
                ),
            ],
            database_operations=[],
        ),
    ]