# Generated by Django 5.2.5 on 2025-08-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia_horarios", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["dia_semana", "inicio", "fin"],
                name="academia_ho_dia_sem_cb4c98_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="timeslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("inicio__lt", models.F("fin"))),
                name="timeslot_inicio_lt_fin",
            ),
        ),
        migrations.AlterModelTable(
            name="docente",
            table=None,
        ),
        migrations.AlterModelTable(
            name="horarioclase",
            table=None,
        ),
        migrations.AlterModelTable(
            name="materia",
            table=None,
        ),
        migrations.AlterModelTable(
            name="periodo",
            table=None,
        ),
        migrations.AlterModelTable(
            name="plan",
            table=None,
        ),
        migrations.AlterModelTable(
            name="profesorado",
            table=None,
        ),
        migrations.AlterModelTable(
            name="timeslot",
            table=None,
        ),
    ]
