# Generated by Django 5.2.5 on 2025-08-30 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academia_horarios", "0002_timeslot_academia_ho_dia_sem_cb4c98_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="comision",
            table="academia_horarios_comision",
        ),
        migrations.AlterModelTable(
            name="docente",
            table="academia_horarios_docente",
        ),
        migrations.AlterModelTable(
            name="horarioclase",
            table="academia_horarios_horarioclase",
        ),
        migrations.AlterModelTable(
            name="materia",
            table="academia_horarios_materia",
        ),
        migrations.AlterModelTable(
            name="materiaenplan",
            table="academia_horarios_materiaenplan",
        ),
        migrations.AlterModelTable(
            name="periodo",
            table="academia_horarios_periodo",
        ),
        migrations.AlterModelTable(
            name="plan",
            table="academia_horarios_plan",
        ),
        migrations.AlterModelTable(
            name="profesorado",
            table="academia_horarios_profesorado",
        ),
        migrations.AlterModelTable(
            name="timeslot",
            table="academia_horarios_timeslot",
        ),
    ]
