# Generated by Django 5.2.5 on 2025-08-30 07:41

from django.db import migrations, models

TABLE = "academia_horarios_horarioclase"

def only_mysql_do(apps, schema_editor):
    """
    Ejecuta operaciones de base de datos solo en MySQL.
    """
    if schema_editor.connection.vendor != "mysql":
        return
    
    # Si necesitas tocar índices "viejos" o realizar una acción específica
    # a nivel de base de datos en MySQL, puedes añadir el SQL aquí.
    # Por ejemplo, para borrar un índice cuyo nombre es problemático para Django:
    # with schema_editor.connection.cursor() as cursor:
    #     cursor.execute("ALTER TABLE academia_horarios_horarioclase DROP INDEX `nombre_del_indice_viejo`;")
    pass

def only_mysql_undo(apps, schema_editor):
    """
    Operación de rollback opcional para MySQL.
    """
    if schema_editor.connection.vendor != "mysql":
        return
    # Aquí iría el código para revertir lo que hiciste en only_mysql_do.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("academia_horarios", "0008_relax_comision_legacy_columns"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Esta sección solo afecta a la base de datos real.
            # El RunPython se asegura de que solo se ejecute en MySQL.
            database_operations=[
                migrations.RunPython(only_mysql_do, only_mysql_undo),
            ],
            
            # Esta sección solo afecta el "estado" de los modelos de Django.
            # Permite que las futuras migraciones se creen correctamente
            # sin intentar ejecutar SQL potencialmente problemático en SQLite.
            state_operations=[
                # Aquí están las operaciones originales de esta migración.
                migrations.AlterUniqueTogether(
                    name="horarioclase",
                    unique_together=set(),
                ),
                migrations.AddConstraint(
                    model_name="horarioclase",
                    constraint=models.UniqueConstraint(
                        fields=("comision", "timeslot"), name="uniq_horario_por_comision_bloque"
                    ),
                ),
            ],
        )
    ]
