# Generated by Django 5.2.5 on 2025-08-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia_horarios", "0008_relax_comision_legacy_columns"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="horarioclase",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="horarioclase",
            constraint=models.UniqueConstraint(
                fields=("comision", "timeslot"), name="uniq_horario_por_comision_bloque"
            ),
        ),
    ]
