# Generated by Django 5.2.5 on 2025-08-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia_horarios", "0009_alter_horarioclase_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="materiaenplan",
            name="horas_catedra",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Cantidad semanal de horas cátedra (40’). Dejar vacío = sin tope.",
                null=True,
            ),
        ),
    ]
