# Generated by Django 5.2.5 on 2025-08-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academia_horarios", "0010_materiaenplan_horas_catedra"),
    ]

    operations = [
        migrations.AddField(
            model_name="docente",
            name="dni",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
