# Generated by Django 5.2.5 on 2025-08-30 09:05

from django.db import migrations, models

TABLE = "academia_horarios_docente"

def only_mysql_do(apps, schema_editor):
    """
    Ejecuta operaciones de base de datos personalizadas solo en MySQL.
    """
    if schema_editor.connection.vendor != "mysql":
        return
    # ⬇️ Opcional: si la operación estándar falla en MySQL, puedes
    # ejecutar el ALTER TABLE real aquí.
    # schema_editor.execute(
    #     f"ALTER TABLE {TABLE} ADD COLUMN dni VARCHAR(20) NULL UNIQUE;"
    # )
    pass

def only_mysql_undo(apps, schema_editor):
    """
    Operación de rollback opcional para MySQL.
    """
    if schema_editor.connection.vendor != "mysql":
        return
    # rollback opcional
    # schema_editor.execute(f"ALTER TABLE {TABLE} DROP COLUMN dni;")
    pass

class Migration(migrations.Migration):
    dependencies = [
        # La dependencia correcta de tu archivo original
        ("academia_horarios", "0010_materiaenplan_horas_catedra"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Esta sección está lista para cualquier SQL específico que
            # necesites ejecutar solo en MySQL.
            database_operations=[
                migrations.RunPython(only_mysql_do, only_mysql_undo),
            ],

            # Esta sección actualiza el estado de Django para reflejar
            # que el modelo Docente ahora tiene un campo 'dni'.
            state_operations=[
                migrations.AddField(
                    model_name="docente",
                    name="dni",
                    field=models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
            ],
        )
    ]
